# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
env:
  phases:
  pre_build:
    commands:
      #installs dependencies into the node_modules/ directory
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
  build:
    commands:
      - mvn test
  post_build:
      - mvn sonar:sonar -Dsonar.login=4adc8127ccd49a813e0f3c919dfa1465cda30dcc -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=shivareddy712_covid19 -Dsonar.organization=shivareddy712
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
# Include only the files required for your application to run.
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
    - scripts/**/*
